version: "3"
services:
  db:
    image: postgres # Consider using pgAdmin: www.pgadmin.org for browsing postgres DB
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123